name: Build Pico Loader

on:
  push:
    branches: ["develop"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["develop"]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  pico_loader:
    strategy:
      matrix:
        platform: [
          "ACE3DS",
          "AK2",
          "AKRPG",
          "DSPICO",
          "DSTT",
          "EZP",
          "G003",
          "M3DS",
          "R4",
          "R4iDSN",
          "SUPERCARD"
        ]
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-v1.13.1
    name: Build Pico Loader
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Run build script
        run: |
          make PICO_PLATFORM=${{ matrix.platform }}
          mv picoLoader7.bin data/picoLoader7.bin
          mv picoLoader9_${{ matrix.platform }}.bin data/picoLoader9.bin
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: |
            data/aplist.bin
            data/savelist.bin
            data/picoLoader7.bin
            data/picoLoader9.bin
          name: Pico Loader for ${{ matrix.platform }}
